config/routes.rb
MutualAidSocialNetwork::Application.routes.draw do  
  
  scope "(:locale)", locale: /en|ru/ do	
    get "records/index"

    get "static_pages/about"

    get "static_pages/help"

    get "static_pages/contact"

	match '/signup',  to: 'users#new'
	controller :sessions do
	  get 'signin' => :new
	  post 'signin' => :create
	  delete 'signout' => :destroy
	end

    resources :users
    resources :cans, excpect: [:index]
    resources :needs, excpect: [:index]  
    
	root :to => 'sessions#new'
  end

end

app/models/need.rb
class Need < ActiveRecord::Base
  attr_accessible :deadline, :executed, :long_description, :short_description, :sphere, :when_executed, :who_executed

  MODES = ["Need", "Can"]
  SPHERE_TYPES = ["Psychological assistance", "Household", "Study", "Ideas for a creative", "Scientific activity", "Other"]
  
  belongs_to :user
  
  validates :user_id, presence: true
  validates :short_description, presence: true
  validates :long_description, presence: true
  validates :sphere, presence: true
  
  default_scope order: 'needs.created_at DESC'
  
  def self.search(search)
    if search
      find(:all, :conditions => ['sphere LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  before_filter :signed_in_user

  def index
	  @needs = Need.all
	
	  respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end
  
  def new
    @need = Need.new
  end
  
  def edit
    @users = User.all
    @need = Need.find(params[:id])
  end

  def create
    @need = current_user.needs.build(params[:need])
	if @need.save
      flash[:success] = "Need created!"
      redirect_to current_user
	else
	  render current_user
	end
  end
  
  def update
    @need = Need.find(params[:id])
	if @need.update_attributes(params[:need])
	  flash[:success] = "Need updated!"
      redirect_to current_user
    else
      render current_user
    end
  end

  def destroy
    @need = Need.find(params[:id])
    @need.destroy
	redirect_to current_user
  end

end

app/views/needs/_need.html.erb
<li>
  <p>
    <strong><%= t(:Short_description) %> </strong><%= need.short_description %>
  </p>

  <p>
    <strong><%= t(:Sphere) %> </strong><%= need.sphere %>
  </p>
  
  <p>  
    <strong><%= t(:Long_description) %> </strong><%= need.long_description %>
  </p>
  
  <p>  
    <strong><%= t(:Deadline) %> </strong><%= need.deadline.to_s(:ru_datetime) %>
  </p>
  
  <% if need.executed? %>
    <p> 
	  <strong><%= t(:Executed!) %> </strong> 
	</p>
	
	<p>  
      <strong><%= t(:Who_executed) %> </strong> <%= User.find(need.who_executed).name + " " + User.find(need.who_executed).surname %>
    </p>
	
	<p>  
      <strong><%= t(:When_executed) %> </strong><%= need.when_executed.to_s(:ru_datetime) %>
    </p>
  <% end %>
  
  <% if current_user?(need.user) %>
    <%= link_to t(:edit), edit_need_path(need) %> |
    <%= link_to t(:delete), need, method: :delete,
                                     data: { confirm: t(:Are_you_sure?) } %>
  <% end %>
</li>

app/views/needs/edit.html.erb
<%= form_for(@need) do |f| %>
  <p>
    <%= f.label :short_description, t(:short_description) %><br />
    <%= f.text_field :short_description %>
  </p>
  <p>
    <%= f.label :sphere, t(:sphere) %><br />
	<%= f.select :sphere, Need::I18n.translate(:SPHERE_TYPES) %>
  </p>  
  <p>
    <%= f.label :long_description, t(:long_description) %><br />
	<%= f.text_area :long_description %>
  </p>	
  <p>
    <%= f.label :deadline, t(:deadline) %><br />
	<%= f.date_select :deadline, :order => [:day, :month, :year] %>
  </p>
    <%= f.label :executed, t(:executed) %><br />
    <%= f.check_box :executed %>
  <br />
  <p>
  </p>
  <p>
    <%= f.label :who_executed, t(:Who_executed) %><br />
	<%= f.select :who_executed, users_names %>
  </p>	
  <p>
    <%= f.label :when_executed, t(:When_executed) %><br />
	<%= f.date_select :when_executed, :order => [:day, :month, :year] %>
  </p>
  <p>
    <%= f.submit t(:Update_Need), class: "btn btn-large btn-primary" %>
  </p>
<% end %>

app/views/needs/index.html.erb
<h1>Needs</h1>

	<ul class="users">
		<% @needs.each do |need| %>
		  <li>
		    <div class="row">
			  <aside class="span4">
				<%= link_to need.user.name + " " + need.user.surname, need.user %><br />
				<%= need.user.date_of_birth.to_s(:ru_datetime) %>
				<%= need.user.country %>
				<%= need.user.city %>
				<%= need.user.education %><br />
				<%= need.user.member_of_volunteer_organizations %><br />
				<%= need.user.email %>
				<%= need.user.phone_number %>
				<%= need.user.other_contacts %><br />
			  </aside>
			  <div class="span8">
				  <%= need.short_description %>   <%= need.sphere %><br />
				  <%= need.long_description %> <br />
				<br />
			  </div>
			</div>
		  </li>	
	    <% end %>
	</ul>

app/views/needs/new.html.erb
<%= form_for(@need) do |f| %>
  <p>
    <%= f.label :short_description, t(:short_description) %><br />
    <%= f.text_field :short_description %>
  </p>
  <p>
    <%= f.label :sphere, t(:sphere) %><br />
	<%= f.select :sphere, Need::I18n.translate(:SPHERE_TYPES)%>
  </p>  
  <p>
    <%= f.label :long_description, t(:long_description) %><br />
	<%= f.text_area :long_description %>
  </p>	
  <p>
    <%= f.label :deadline, t(:deadline) %><br />
	<%= f.date_select :deadline, :order => [:day, :month, :year] %>
  </p>
  <p>
    <%= f.submit t(:Create_Need), class: "btn btn-large btn-primary" %>
  </p>
<% end %>