config/routes.rb
MutualAidSocialNetwork::Application.routes.draw do  
  
  scope "(:locale)", locale: /en|ru/ do	
    get "records/index"

    get "static_pages/about"

    get "static_pages/help"

    get "static_pages/contact"

	match '/signup',  to: 'users#new'
	controller :sessions do
	  get 'signin' => :new
	  post 'signin' => :create
	  delete 'signout' => :destroy
	end

    resources :users
    resources :cans, excpect: [:index]
    resources :needs, excpect: [:index]  
    
	root :to => 'sessions#new'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  after_destroy :ensure_an_admin_remains
  before_save { |user| user.email = email.downcase }
  before_save { |user| user.login = login.downcase }
  before_save :create_remember_token
  
  attr_accessible :city, :country, :date_of_birth, :education, :email, :login, :member_of_volunteer_organizations, :name, :other_contacts, :phone_number, :surname, :password, :password_confirmation, :avatar, :show_date_of_birth
  has_secure_password
  
  has_many :cans, dependent: :destroy
  has_many :needs, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
  
  
  validates :login, presence: true, uniqueness: true
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }, 
	uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
    
  def admin?
    admin
  end
  
  private
	def ensure_an_admin_remains
	  if User.count.zero?
		raise "Last user can\'t be deleted"
	  end
    end

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end	

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :show, :edit, :update, :delete]
  before_filter :correct_user,   only: [:edit, :update]
  
  # GET /users
  # GET /users.json
  def index
	@users = User.all
	
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
	@cans = @user.cans
	@needs = @user.needs

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
	    sign_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update  
    respond_to do |format|
      if @user.update_attributes(params[:user])
	    sign_in @user
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
	begin
	  @user.destroy
	  flash[:notice] = "User #{@user.name} deleted"
	rescue Exception => e
	  flash[:notice] = e.message
	end	
	
    @user.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  private
  	
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="row">
  <div class="span6 offset3">

<%= form_for @user, :html => {:multipart => true} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login, t(:Login) + "*" %><br />
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :password, t(:Password) + "*:" %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, t(:Password_Confirmation) + "*:" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :avatar, t(:Avatar) + "*:"  %><br />
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :name, t(:Name) + "*:" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname, t(:Surname) + ":" %><br />
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :show_date_of_birth, t(:Show_date_of_birth) + ":" %><br />
    <%= f.check_box :show_date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth, t(:Date_of_birth) + ":" %><br />
    <%= f.date_select :date_of_birth, order: [:day, :month, :year], start_year: 1900 %>
  </div>
  <div class="field">
    <%= f.label :country, t(:Country) + ":" %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :city, t(:City) + ":" %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :education, t(:Education) + ":" %><br />
    <%= f.text_field :education %>
  </div>
  <div class="field">
    <%= f.label :member_of_volunteer_organizations, t(:Member_of_volunteer_organizations) + ":" %><br />
    <%= f.text_field :member_of_volunteer_organizations %>
  </div>
  <div class="field">
    <%= f.label :email, t(:Email) + "*:" %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_number, t(:Phone_number) + ":" %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :other_contacts, t(:Other_contacts) + ":" %><br />
    <%= f.text_field :other_contacts %>
  </div>
  <div class="actions">
    <%= f.submit t(:Apply), class: "btn btn-large btn-primary" %>
  </div>
<% end %>
* <%= t(:fields_must_be_fill_in) %><br />

  </div>
</div>

app/views/users/edit.html.erb
<h1><%= t(:Settings) %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1><%= t(:Users) %></h1>

  	<ul class="users">
		<% @users.each do |user| %>
		  <li id="user<%= user.id %>">
		    <div class="row">
			  <aside class="span4">
				  <% if user.avatar_url != nil %>
				    <div class="small_avatar" id="<%= user.id %>">
				      <%= image_tag user.avatar_url.to_s, size: "125x75" %>
					</div>
				  <% end %> 
				<div id="link<%= user.id %>">  
				  <%= link_to user.name + " " + user.surname, user %><br />
				</div>   
				<%= user.date_of_birth.to_s(:ru_datetime) %>
				<%= user.country %>
				<%= user.city %>
				<%= user.education %><br />
				<%= user.member_of_volunteer_organizations %><br />
				<%= user.email %>
				<%= user.phone_number %>
				<%= user.other_contacts %><br />

				<% if current_user.admin? && !current_user?(user) %>
				  <%= link_to t(:Destroy), user, method: :delete, data: { confirm: t(:Are_you_sure?) } %>
				<% end %>
			  </aside>
			  <div class="span8">
				<% if user.needs.any? %>
				  <strong><%= t(:I_need) %></strong><br />
				  <%= user.needs.first.short_description %>   <%= user.needs.first.sphere %><br />
				  <%= truncate(strip_tags(user.needs.first.long_description), length: 80) %> <br />
				<% end %>  
				<br />
				<% if user.cans.any? %>
				  <strong><%= t(:I_can) %></strong><br />
				  <%= user.cans.first.short_description %>   <%= user.cans.first.sphere %><br />
				  <%= truncate(strip_tags(user.cans.first.long_description), length: 80) %> <br />
				<% end %>  
			  </div>
			</div>
		  </li>	
	    <% end %>
	</ul>

app/views/users/new.html.erb
<h1><%= t(:Please_Sign_Up) %></h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
  <aside class="span4">
    <section>

		<p id="notice"><%= notice %></p>
		
		<% if @user.avatar_url != nil %>
		  <p>
		    <%= image_tag @user.avatar_url.to_s, size: "250x150" %>
		  </p>
		<% end %>
		
		<p>
		  <b><%= t(:Name)  %></b>
		  <%= @user.name %>
		</p>

		<p>
		  <b><%= t(:Surname) %></b>
		  <%= @user.surname %>
		</p>
		
		<% if @user.show_date_of_birth %>
		  <p>
		    <b><%= t(:Date_of_birth) %></b>
		    <%= @user.date_of_birth.to_s(:ru_datetime) %>
		  </p>
		<% end %>
		
		<p>
		  <b><%= t(:Country) %></b>
		  <%= @user.country %>
		</p>

		<p>
		  <b><%= t(:City) %></b>
		  <%= @user.city %>
		</p>

		<p>
		  <b><%= t(:Education) %></b>
		  <%= @user.education %>
		</p>

		<p>
		  <b><%= t(:Member_of_volunteer_organizations) %></b>
		  <%= @user.member_of_volunteer_organizations %>
		</p>

		<p>
		  <b><%= t(:Email) %></b>
		  <%= @user.email %>
		</p>

		<p>
		  <b><%= t(:Phone_number) %></b>
		  <%= @user.phone_number %>
		</p>

		<p>
		  <b><%= t(:Other_contacts) %></b>
		  <%= @user.other_contacts %>
		</p>
		
		<% if @user == current_user %>
		  <%= link_to t(:Create_Can), new_can_path %> |
		  <%= link_to t(:Create_Need), new_need_path %> |
		  <%= link_to t(:Edit_Profile), edit_user_path(@user) %>
		<% end %>  

	</section>
  </aside>

  <div class="span8">

	<% if @user.needs.any? %>
	  <h3><%= t(:I_need) %></h3>
	  <ol class="cans-needs">
		<%= render @needs %>
	  </ol>
	<% end %>

	<% if @user.cans.any? %>
	  <h3><%= t(:I_can) %></h3>
	  <ol class="cans-needs">
		<%= render @cans %>
	  </ol>
	<% end %>

  </div>
</div>