config/routes.rb
MutualAidSocialNetwork::Application.routes.draw do  
  
  scope "(:locale)", locale: /en|ru/ do	
    get "records/index"

    get "static_pages/about"

    get "static_pages/help"

    get "static_pages/contact"

	match '/signup',  to: 'users#new'
	controller :sessions do
	  get 'signin' => :new
	  post 'signin' => :create
	  delete 'signout' => :destroy
	end

    resources :users
    resources :cans, excpect: [:index]
    resources :needs, excpect: [:index]  
    
	root :to => 'sessions#new'
  end

end

app/models/can.rb
class Can < ActiveRecord::Base
  attr_accessible :long_description, :sphere, :short_description
  
  belongs_to :user
  validates :sphere, presence: true
  validates :long_description, presence: true
  validates :short_description, presence: true
  validates :user_id, presence: true
  
  default_scope order: 'cans.created_at DESC'
    
  def self.search(search)
    if search
      find(:all, :conditions => ['sphere LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/cans_controller.rb
class CansController < ApplicationController
  before_filter :signed_in_user

  def index
      @cans = Can.all
	
	  respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end
  
  def new
    @can = Can.new
  end
  
  def edit
    @can = Can.find(params[:id])
  end

  def create
    @can = current_user.cans.build(params[:can])
	if @can.save
      flash[:success] = "Can created!"
      redirect_to current_user
	else
	  render current_user
	end
  end
  
  def update
    @can = Can.find(params[:id])
	if @can.update_attributes(params[:can])
	  flash[:success] = "Micropost created!"
      redirect_to current_user
    else
      render current_user
    end
  end

  def destroy
    @can = Can.find(params[:id])
    @can.destroy
	redirect_to current_user
  end

end

app/views/cans/_can.html.erb
<li>
  <p>
    <strong><%= t(:Short_description) %> </strong><%= can.short_description %>
  </p>
  
  <p>
    <strong><%= t(:Sphere) %></strong> <%= can.sphere %>
  </p>

  <p>  
    <strong><%= t(:Long_description) %> </strong><%= can.long_description %>
  </p>
  <% if current_user?(can.user) %>
    <%= link_to t(:edit), edit_can_path(can) %> |
    <%= link_to t(:delete), can, method: :delete,
                                     data: { confirm: t(:Are_you_sure?) } %>
  <% end %>
</li>

app/views/cans/edit.html.erb
<%= form_for(@can) do |f| %>
  <p>
    <%= f.label :short_description, t(:short_description) %><br />
    <%= f.text_field :short_description %>
  </p>	
  <p>
    <%= f.label :sphere, t(:sphere) %><br />
	<%= f.select :sphere, Need::I18n.translate(:SPHERE_TYPES) %>
  </p> 
  <p>
    <%= f.label :long_description, t(:long_description) %><br />
	<%= f.text_area :long_description %>
  </p>	
  <p>
    <%= f.submit t(:Update_Can), class: "btn btn-large btn-primary"  %>
  </p>
<% end %>

app/views/cans/index.html.erb
<h1>Cans</h1>

	<ul class="users">
		<% @cans.each do |can| %>
		  <li>
		    <div class="row">
			  <aside class="span4">
				<%= link_to can.user.name + " " + can.user.surname, can.user %><br />
				<%= can.user.date_of_birth.to_s(:ru_datetime) %>
				<%= can.user.country %>
				<%= can.user.city %>
				<%= can.user.education %><br />
				<%= can.user.member_of_volunteer_organizations %><br />
				<%= can.user.email %>
				<%= can.user.phone_number %>
				<%= can.user.other_contacts %><br />
			  </aside>
			  <div class="span8">
				  <%= can.short_description %>   <%= can.sphere %><br />
				  <%= can.long_description %> <br />
				<br />
			  </div>
			</div>
		  </li>	
	    <% end %>
	</ul>

app/views/cans/new.html.erb
<%= form_for(@can) do |f| %>
  <p>
    <%= f.label :short_description, t(:short_description) %><br />
    <%= f.text_field :short_description %>
  </p>	
  <p>
    <%= f.label :sphere, t(:sphere) %><br />
	<%= f.select :sphere, Need::I18n.translate(:SPHERE_TYPES) %>
  </p> 
  <p>
    <%= f.label :long_description, t(:long_description) %><br />
	<%= f.text_area :long_description %>
  </p>	
  <p>
    <%= f.submit t(:Create_Can), class: "btn btn-large btn-primary" %>
  </p>
<% end %>