config/routes.rb
MutualAidSocialNetwork::Application.routes.draw do  
  
  scope "(:locale)", locale: /en|ru/ do	
    get "records/index"

    get "static_pages/about"

    get "static_pages/help"

    get "static_pages/contact"

	match '/signup',  to: 'users#new'
	controller :sessions do
	  get 'signin' => :new
	  post 'signin' => :create
	  delete 'signout' => :destroy
	end

    resources :users
    resources :cans, excpect: [:index]
    resources :needs, excpect: [:index]  
    
	root :to => 'sessions#new'
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t(:mutual_assistance_social_NET) %>
  </small>
  <nav>
    <ul>
	  <li><%= link_to t(:Help), static_pages_help_path %></li>
      <li><%= link_to t(:About),   static_pages_about_path %></li>
      <li><%= link_to t(:Contact), static_pages_contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
	  <% if current_user != nil %>
	    <%= link_to t(:Hello) + ", #{current_user.name + " " + current_user.surname}", user_path(current_user), class: "brand" %>
	  <% end %>
	  <nav>
	  	<ul class="nav pull-right">
		  <% if signed_in? %>
		    <li><%= link_to t(:Users), users_path %></li>
            <li><%= link_to t(:Settings), edit_user_path(current_user) %></li>
			<li><%= link_to t(:Sign_out), signout_path, method: "delete" %></li>
            <!--<li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign_out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>-->
		  <% else %>
			<li><%= link_to t(:Sign_In), signin_path %></li>	
		  <% end %>
		  <li><%= link_to t(:russian), users_path(:locale => :ru) %></li>
          <li><%= link_to t(:english), users_path(:locale => :en) %><li>
		</ul>
	  </nav>
	</div>
  </div>
</div>
</header>

app/views/layouts/_search.html.erb
<%= form_tag records_index_path, method: :get do %>
	  <div class="search offset7">
        <%= select_tag "mode", options_for_select(Need::I18n.translate(:MODES), params[:mode]) %>
	    <%= select_tag "search", options_for_select(Need::I18n.translate(:SPHERE_TYPES), params[:search]) %>
		<%= submit_tag t(:Search), name: nil, class: "btn btn-search" %>
	  </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MutualAidSocialNetwork</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

<%= render 'layouts/header' %>

<% if signed_in? %>
  <%= render 'layouts/search' %>
<% end %>  


<div class="container">
  <%= yield %>
<div>  

<%= render 'layouts/footer' %>

<% if Rails.env.development? && current_user %>
  <%= current_user.id %>
  <%= current_user.login %>
  <%= current_user.remember_token %>
  <%= debug(params) %>
<% end %>

</body>
</html>